[metadata]
name = dri-voyager-preppy
version = 1.1.0
author = Seth Parker
author_email = c.seth.parker@uky.edu
description = Mesh preparation for DRI Voyager
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.com/educelab/dri-voyager-preppy
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.11
install_requires =
    natsort
    Pillow
    tqdm

[options.packages.find]
include = preppy*
exclude = test

[options.entry_points]
console_scripts =
    voyager-preppy = preppy.apps.file_prep:main
    voyager-obj2glb = preppy.apps.obj_to_glb:main
    voyager-merge-items = preppy.apps.merge_items:main
