[metadata]
name = dri-voyager-preppy
version = 1.0.0
author = Seth Parker
author_email = c.seth.parker@uky.edu
description = Mesh preparation for DRI Voyager
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.com/educelab/dri-voyager-preppy
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.9

[options.packages.find]
include = apps*
exclude = test

[options.entry_points]
console_scripts =
    voyager-preppy = apps.preppy:main
